### ISSUE TITLE
sidebar: no stats on first mailbox

### ISSUE THREAD

**Issue by Austin-Ray** [neomutt/neomutt#1380]
## Expected Behaviour

Sidebar should have unread and total message counts.

## Actual Behaviour

Sidebar displays 0 for unread and total message counts.

If `virtual-mailboxes`, modifying tags, changing mailboxes, or opening the browser will cause stats to update.

Unable to get stats to update for maildir. Have not tried IMAP.

## Steps to Reproduce

1. Make sure your `sidebar_format` contains unread and total message counts
2. Open NeoMutt
3. Check stats. Should display 0 for message counts.

## How often does this happen?

- Always

## When did it start to happen?

After architectural changes

**Comment by Austin-Ray** [comment]
Fixed in f03ca7fb4ad38f69751c06e8153708893637400b

**Comment by N8Fear** [comment]
I don't have any stats on any mailbox (in the sidebar) until I manually changed the folder. f03ca7f doesn't fix it for me.
I'm using IMAP.

**Comment by Austin-Ray** [comment]
@N8Fear Could you try building off the latest commit?

This issue occurred due to the architectural changes and behavior now matches pre-architectural changes behavior. I may have messed up my `git bisect` for the fix's commit.

**Comment by N8Fear** [comment]
The offending commit is cd3ea66ae37f68efa814e89d220c43c76255670d - at least, if I revert it, I get stats in the sidebar again. On the other hand this leads to segfaults on switching folders again.

**Comment by Austin-Ray** [comment]
@N8Fear: Thanks for the bisect. I don't use IMAP often so I'm not familiar with that part of the code.

@flatcap: Any ideas?

**Comment by sileht** [comment]
I have the same issue on imap

**Comment by N8Fear** [comment]
#1396 still has some issues. While I have stats now, the unread count is set to "real unread count" * "times opening the folder".

**Comment by sileht** [comment]
The wrong count issue doesn't looks related to the imap connection issue.

We can also see that the `old`/`new` in status bar is also wrong.

It think `ctx->new` is not reseted somewhere or something like that..

**Comment by sileht** [comment]
For the wrong count I have proposed a fix here: https://github.com/neomutt/neomutt/pull/1401

Maybe other backend will need the same kind of fix.

**Comment by sileht** [comment]
I think all fixes for imap have been merged, can you retest ?

**Comment by arbrandes** [comment]
Not the OP, but I just built the latest master and it does fix all the sidebar issues with IMAP/Maildir.  Thanks!
