### ISSUE TITLE
neomutt 2019-10-25 fails to suggest mailboxes with new mail

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1881]
## Expected Behaviour

Switch to the next mailbox with new mail by pressing `c`, Space, Space, Space Enter

## Actual Behaviour

No mailboxes are suggested while I keep pressing Space.

## Steps to Reproduce

Launch neomutt, press `c`.

I can launch the older build (/usr/bin/neomutt, which is 20180716) and it offers me five mailboxes with new mail (IN.root, IN.gitub etc.).

I can open the sidebar and I see that the new neomutt also acknowledges that those five mailboxes have new mail.  (For some reason the new neomutt shows _all_ inboxes, while the old one shows only those with new mail.)

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use? 20180716

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.3.0-19-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.12.0
hcache backends: tokyocabinet

Compiler:
cc (Ubuntu 9.2.1-9ubuntu1) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Ubuntu 19.10
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local maildirs

**Comment by mgedmin** [comment]
I'm wondering if this might be a consequence of some memory corruption valgrind has seen while I was debugging #1880.

**Comment by mgedmin** [comment]
Nope, I can get rid of the segfault by removing my folder-hooks that do `unmailboxes *`, but the new neomutt still won't offer me mailboxes with new mail in the `c` prompt, despite showing them having new mail in the sidebar.

**Comment by Fuzzbox999** [comment]
Hi, same bug with Arch Linux, neomutt 2019-10-25.

**Comment by mgedmin** [comment]
For the record, neomutt -z/-Z also doesn't notice new mail.

**Comment by fbellet** [comment]
In my case, where the ``<change-folder>`` command now fails to suggest the first folder having new messages, bisecting reveals that it is related to commits bfdd5b1f1 and c11dbf982. It seems to be caused by function ``maildir_check_dir()`` that just sets the ``m->has_new flag``, and doesn't increment the ``m->msg_new`` counter.

**Comment by brianbuccola** [comment]
Relatedly, neomutt now fails to issue a beep/bell upon new mail.

**Comment by gahr** [comment]
should be fixed by 0e19dd15dfb9786c0bfd733a2ba76595087b238d I suppose?

**Comment by fbellet** [comment]
Yes it's fixed with 0e19dd1, thank you!

**Comment by brianbuccola** [comment]
I'm still having an issue here. Normally, (neo)mutt alerts me that a mailbox has new mail. By "alert", I mean two things:

1. Neomutt displays `New mail in =mailboxname` at the bottom left of the window.
2. Neomutt issues a beep/bell to the terminal.

In addition (and again, normally), neomutt also does this:

3. I can press `c` so that neomutt suggests changing to the mailbox with new mail.

Before this issue was fixed, neomutt would do **none** of 1, 2, or 3.

Since this issue was fixed/close, 3 (pressing `c`) has returned to normal behavior.

However, 1 and 2 are still abnormal (but in a different way): neomutt now only issues an alert message and terminal beep **one time** (per mailbox). After that, it fails to issue any more alert messages or beeps when new mail arrives, unless I close neomutt and re-open it. Then it issues just one alert/beep again, and then stops alerting again.

Is anyone else experiencing this? (I hope the description makes sense.)

I can also open a new issue, if that makes more sense.

Thanks.

**Comment by flatcap** [comment]
@brianbuccola 
Sorry, 'new mail' has been a bit of a mess recently.
gahr noticed and just fixed one final problem with the new mail detection/notification.
Please can you try building from `master` (2cc1e12e3 is the fix).

**Comment by brianbuccola** [comment]
Thanks, @flatcap. Just rebuilt, but unfortunately the same issue persists (I get an alert/beep for the first new mail, but nothing more after that).

**Comment by gahr** [comment]
So, there are two cases where the `new_mail_command` is currently triggered

1. the number of new messages in the currently selected mailbox increases
2. the number of mailboxes with new mail increases

I fixes one thing related to point 1. Point 2. still only triggers the command once if mail keeps flowing into the same mailbox, because it tracks the number of **mailboxes** with new messages, not the number of **messages**. Fixing point 2. is not trivial.

**Comment by brianbuccola** [comment]
@gahr, @flatcap, after some testing, I realize it's an issue specific to my virtual mailbox. In simple terms, here's the issue: I have two mailboxes, call them `home` and `work`. I want to check both their inboxes for new mail:

```
# Mailboxes to poll for new mail
mailboxes "+home/inbox" \
          "+work/inbox"
```

I *also* want to be able to view both inboxes in a single window, so I create a virtual mailbox for them:

```
# Virtual mailboxes
set virtual_spoolfile
set nm_query_type = threads
virtual-mailboxes "all" "notmuch://?query=folder:home/indox or folder:work/inbox"
```

When I'm viewing just `+home/inbox`, or just `+work/inbox`, I get an alert message and terminal beep whenever a new mail arrives, in the sense of @gahr's case 1 above. So, no issue there.

**The problem:** When I'm viewing the virtual mailbox `all`, I only get one alert message and terminal beep for the very first new mail that arrives in `+home/inbox`, and the same for the first new mail that arrives in `+work/inbox`, and then after that, I no longer get any alert messages or terminal beeps. (But pressing `c` *does* correctly suggest the mailbox with new mail.)

Does that make sense? Maybe at this point it's worth opening a new issue.

**Comment by gahr** [comment]
Your description of the problem matches with case 2. above, doesn’t it? Let’s keep this issue for the original problem (which was fixed). You can open a separate issue for case 2. but I’m afraid there’s no quick fix. Spoiler alert, it will be fixed when some refactoring we have in the pipeline is done.

**Comment by brianbuccola** [comment]
Ah, I think I understand the distinction between 1 and 2 now: since I'm viewing a *virtual* mailbox (not a *real* mailbox), the new mail alert/beep is only triggered once (per real mailbox), and even though I mark those new mails as read (from the virtual mailbox), the new mail alert/beep is never triggered again, because I'm not actually *viewing* those mailboxes. In other words, new mail keeps flowing into the real mailboxes, but since I'm not viewing them, the new mail alert/beep only gets triggered upon the first new mail received (per mailbox).

Is that correct?

It's interesting/confusing because this was never a problem until the other issue (your case 1 above) arose, which is why I figured they had a related source, and that fixing one would fix the other. But I guess not.

**Comment by gahr** [comment]
Unfortunately I am not knowledgeable regarding virtual mailboxes. Maybe someone with notmuch-foo can chime in.

**Comment by Fuzzbox999** [comment]
Hi. I've tried NeoMutt 20191207 instead of 20180716 and I still experiment this very same behaviour : pressing "c" does not suggest mailboxes with new mail. 

In my .muttrc I've tried to use named-mailboxes and now I have : 

set folder=~/.mutt
#mailboxes "~/.mutt/pro/inbox"
#mailboxes "~/.mutt/perso/inbox"
#mailboxes "~/.mutt/gmail/inbox"
named-mailboxes "Pro" ="pro/inbox"
named-mailboxes "Perso" ="perso/inbox"
named-mailboxes "Gmail" ="gmail/inbox"

but no change. Pressing Tab offers me to change the mailbox I'm in, but that's all.
Any tip ?
