### ISSUE TITLE
Can't jump to unread/new messages

### ISSUE THREAD

**Issue by tribly** [neomutt/neomutt#1897]
I'm using NeoMutt 2019-10-25, and in the previous release I've bound `bind index <Tab>  next-unread-mailbox` and hitting `tab` jumped to the next Mailbox with new mail.

Now, no matter what option I use, it won't jump. I've tried `previous-new-then-unread`, `next-new-then-unread`, `next-unread`, `next-unread-mailbox`, `previous-unread`, `sidebar-next-new` with not only `<Tab>` as the bound key.

## Expected Behaviour

Hitting `Tab` when having `bind index <Tab>  next-unread-mailbox` should switch to the mailbox.

## Actual Behaviour

Not switching mailbox and saying we don't have new mail.

## Steps to Reproduce

Updating from `2018 07 16-8` to `2019 10 25-1`

## How often does this happen?

Always

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
  - Arch Linux
* Were you using multiple copies of NeoMutt at once?
  - No
* Were you using 'screen' or 'tmux'?
  - No
* Is your email local (maildir) or remote (IMAP)?
  - Local

**Comment by gahr** [comment]
Can you please try to build from master? This should be fixed after 0e19dd15dfb9786c0bfd733a2ba76595087b238d

**Comment by jbernard** [comment]
I’m not sure if I’m seeing what the bug author is seeing, but at least for imap/fastmail this is still an issue.  It appears that although when the unread count is set to 0 upon sync or change-folder, the new mail flag `N` remains locally (I can see it’s updated on the server) and this causes the change-folder command to continue to want to open the same folder in a loop and never consider the others.

**Comment by tribly** [comment]
> Can you please try to build from master? This should be fixed after [0e19dd1](https://github.com/neomutt/neomutt/commit/0e19dd15dfb9786c0bfd733a2ba76595087b238d)

The new release on Arch Linux has that commit and for me it's working properly again. Thanks!

**Comment by jbernard** [comment]
I think what I'm seeing is a bit different and appears to be captured in #1938

**Comment by roccoblues** [comment]
Closing since the original issue was reported as fixed.
