### ISSUE TITLE
"Encrypted connection unavailable" with IMAP

### ISSUE THREAD

**Issue by bergentroll** [neomutt/neomutt#1910]
## Expected Behaviour

Open neomutt and get list of emails.

## Actual Behaviour

Getting "Encrypted connection unavailable" error message.

## Steps to Reproduce

- Set connection to IMAP (not secure) server.
- Run neomutt.

## How often does this happen?

- Always

## When did it start to happen?

- Seems when I upgraded: `upgraded neomutt (20180716-8 -> 20191025-1)`.

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-2-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

I am on Archlinux GNU/Linux distribution with latest neomutt from repo. I also tried git version g71b81b594 with the same result.

I am using [DavMail](http://davmail.sourceforge.net/) as local IMAP/SMTP server without encryption. My connection string is `set folder = "imap://$my_mailserver:1143/"` where `set my_mailserver = 'localhost'`.

Everything works fine before the latest release, and also mutt and Thunderbird work fine now. Also neomutt works fine with my SSL secured IMAP mailbox.

**Comment by gahr** [comment]
Try setting `ssl_force_tls` to `false` in your config - we merged a change from upstream some time back and we now try to secure all connections by default.

**Comment by bergentroll** [comment]
@gahr, that was the cause, thank you.

**Comment by ernstki** [comment]
> Try setting `ssl_force_tls` to `false` in your config - we merged a change from upstream some time back and we now try to secure all connections by default.

You might want to put this before _before_ the `mailboxes` line in your config, otherwise you'll still get the warning — at least in version 20240329_0 which is the one currently available in MacPorts.

Because I had four or five `mailboxes`, I was getting the terminal bell and warning message for each one, which was pretty annoying, and that led me here. So thanks for the workaround!
