### ISSUE TITLE
Folders disappear from folder list when saving messages

### ISSUE THREAD

**Issue by Kdecherf** [neomutt/neomutt#2199]
## Expected Behaviour

When you want to save a message and list the folders (using `?`), you should see all folders matching the filter.

## Actual Behaviour

After saving a message in a given folder, the folder will not appear anymore in the list of folders when you try to save another message.

Restarting neomutt will resurrect the missing folder in the list

## Steps to Reproduce

1. Save a message
2. Show the list of folders to select the folder you want to save the message into (using `?`)
3. Select a folder (e.g. `FolderA`)
4. Save another message
5. Show the list of folders to select the same folder used on step 2
6. `FolderA` does not appear anymore in the list

## How often does this happen?

- Always

## When did it start to happen?

This issue appeared starting with version `20200313`.

## NeoMutt Version

```
NeoMutt 20200320
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.21 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
libnotmuch: 5.2.0
hcache backends: gdbm

Configure options: --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --prefix=/usr/x86_64-pc-linux-gnu --bindir=/usr/x86_64-pc-linux-gnu/bin --sbindir=/usr/x86_64-pc-linux-gnu/bin --libdir=/usr/x86_64-pc-linux-gnu/lib --datadir=/usr/share --docdir=/usr/share/doc/neomutt-20200320 --infodir=/usr/share/info --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --ssl --homespool --with-homespool=.maildir --with-lock=flock --gdbm --gpgme --disable-idn --idn2 --with-ui=ncurses --notmuch

Compilation CFLAGS: -march=native -O2 -pipe -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/x86_64-pc-linux-gnu/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set -fcntl +flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache +homespool +idn +inotify 
  -locales_hack -lua -lz4 +meta -mixmaster +nls +notmuch +openssl +pgp -sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH=".maildir"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/bin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* maildir+notmuch backend

**Comment by Kdecherf** [comment]
87065d4513c81b69b6d4612f8c02319ddb82e05d seems to be the first bad commit according to a git bisect

**Comment by Kdecherf** [comment]
cc @gahr

**Comment by gahr** [comment]
I cannot reproduce this, with IMAP or local maildir. Can you reproduce the behaviour without NotMuch?

**Comment by Kdecherf** [comment]
I can reproduce the behavior without notmuch support

**Comment by scottkosty** [comment]
I see the same behavior but for changing directories, i.e., using "c" and then `<Tab>`. And a git bisect leads to the same commit, 87065d4. To reproduce, I do the following (note that NeoMutt starts in the folder "INBOX" for me):

1. I press "c" and then `<Tab>`. I already notice a change: "INBOX" is not in the list of options, although it used to be. I don't mind this change since I thought it was a feature: if I'm in "INBOX", I likely don't want to cd to "INBOX".
2. I select "sent".
3. I press "c" and then `<Tab>`. Now both "INBOX" and "sent" are missing from the list.

If I go on selecting folders, they are missing the next time I use "c".

**Comment by scottkosty** [comment]
Here is a minimal config that I can reproduce the problem with:

```
set realname = 'Scott Kostyshak'
set imap_user = 'scott.kostyshak@gmail.com'
set imap_pass = `gpg --use-agent --quiet --batch -d ~/.mdp/per.gpg`

set folder = "~/.mail"

set smtp_url = "smtp://scott.kostyshak@smtp.gmail.com:587/"
set smtp_pass = $imap_pass

set spoolfile = +INBOX
```

**Comment by gahr** [comment]
I shall have a look, try to reproduce, and hopefully fix. Thanks for the info

**Comment by gahr** [comment]
I can reproduce the issue now. Taking a look.

**Comment by scottkosty** [comment]
@gahr 
I can still reproduce the issue in https://github.com/neomutt/neomutt/issues/2199#issuecomment-609448434 with 69a7c76. Perhaps this issue is a separate one? Should I open a separate bug report? Thanks for your work on this!

**Comment by gahr** [comment]
Can you please double check? I'm pretty sure that particular workflow was fixed, as I couldn't reproduce it anymore.

**Comment by scottkosty** [comment]
I just double-checked and still see the issue. Perhaps something is wrong with my setup though (e.g., I need to clear the ccache cache or I have an old file left over from installation of a previous NeoMutt version). I've tested both from an installation and from the local build directly (after a `git clean -xdf`). Here is a screencast in case it helps:

https://www.dropbox.com/s/947sbibbbxrmmho/screencast-LQ-19451.ogv

The screencast goes too fast, sorry about that. But note that I select "r-devel", then in the next time I change directories, "r-devel" is gone. Then I select "r-help". And then the next time it is gone also.

**Comment by gahr** [comment]
Something escapes me here. Are you still using the minimal config you posted earlier?

**Comment by scottkosty** [comment]
> Something escapes me here. Are you still using the minimal config you posted earlier?

The screencast I linked to does not, but I just checked and I can reproduce on current master with the minimal config as well.

@Kdecherf can you check whether the bug is fixed for you on current master?

**Comment by gahr** [comment]
@scottkosty - I run with this config:

```
set folder = ~/Mail/gmail # This is a maildir
set spoolfile = +Inbox
```
Here's my detailed session:

1. Launch neomutt, the Inbox loads
2. press <kbd>c</kbd> for `change-folder`
3. at the `Open mailbox ('?' for list):` prompt I type <kbd>?</kbd>
4. I end up in Mailboxes view, with no mailboxes. Status: `-- NeoMutt: Mailboxes [0]`
5. I press <key>tab</key> for `toggle-mailboxes`
6. I end up in Directory view. Status: `-- NeoMutt: Directory [~/Mail/gmail], File mask: !^\.[^.]`
7. Here I see a directory listing of the files under `~/Mail/gmail`, **including `Inbox`**.
8. I scroll down to `Trash`, hit <kbd>Enter</kbd> and open the `Trash` mailbox
9. I resume from point 2. and when I reach point 7. I still see the same list, **including `Inbox` and `Trash`**

Does this differ in any way from what you are doing?

**Comment by scottkosty** [comment]
@gahr thanks for writing out those steps. I think we figured out the puzzle! If I follow your steps, I cannot reproduce the issue. The difference in our recipes starts with your step 3. In my recipe, I just do "c" and then `<Tab>`, with no `?` in-between. Can you reproduce if you skip step 3 in your recipe?

Thanks for your continued work on this.

**Comment by flatcap** [comment]
@scottkosty Please can you give branch [[devel/c-tab-tab]](https://github.com/neomutt/neomutt/tree/devel/c-tab-tab) a try.

**Comment by scottkosty** [comment]
@flatcap works well! I cannot reproduce the problem with that branch.

**Comment by gahr** [comment]
Thanks @scottkosty and @flatcap :)

**Comment by Kdecherf** [comment]
@scottkosty I'm late to the party, sorry. Current master works as expected, thanks (cc @flatcap)  :+1:

**Comment by scottkosty** [comment]
@Kdecherf thanks for confirming!
