### ISSUE TITLE
Error on Initial run

### ISSUE THREAD

**Issue by mrkreen** [neomutt/neomutt#42]
Might be covered by Issue #39 but I thought I would bring it up. Installed via Homebrew on OS X (10.11.5) and got the following error:

```
/var/mail/[username]: No such file or directory (errno = 2)Segmentation fault: 11
```

**Comment by flatcap** [comment]
@mrkreen 
Thanks for the report.  You're right, it sounds very much like the "keywords" startup bug.
I was planning to make a release next Friday (10th) with the bug fixes.

@alexpearce 
I'd like to create a bug-fix branch and give mrkreen a tweaked copy of the Homebrew formula.
Is it possible to build from a local formula file?

**Comment by alexpearce** [comment]
Yes it is. In fact one can use the remote file directly:

```shell
$ brew install https://raw.githubusercontent.com/neomutt/homebrew-neomutt/master/Formula/neomutt.rb
```

changing `master` to the name of the patch branch. Or one can specify the commit hash:

```shell
$ brew install https://github.com/neomutt/homebrew-neomutt/blob/2a76eaebca3959d5cc2fbfc8753b75024b259c02/Formula/neomutt.rb
```

**Comment by flatcap** [comment]
@alexpearce 
Brilliant.  I'll skip the direct-from-github idea for now.  That'd mean branching the homebrew repo to support bugs in the neomutt repo.

I've tweaked the commit hash and the version number.

@mrkreen 
Please can you try a build using this formula: [neomutt-issue42.rb.txt](https://github.com/neomutt/neomutt/files/298830/neomutt-issue42.rb.txt)  It has the two keywords fixes.
You may need to rename it back to neomutt-issue42.rb
```
$ brew install neomutt-issue42.rb
```

**Comment by mrkreen** [comment]
I try to install neomutt-issue42.rb and get the following:

```
Error: No available formula with the name "neomutt-issue42" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

Tried uninstalling it and got the same thing.

**Comment by flatcap** [comment]
Unfortunately, I'm not a Homebrew expert.
OK, let's try @alexpearce's idea:
```
brew install https://raw.githubusercontent.com/neomutt/homebrew-neomutt/issue/42/Formula/neomutt.rb
```

This time, it should grab the formula directly from our repo.  Good luck :-)

**Comment by flatcap** [comment]
@mrkreen 
I've just released [NeoMutt-20160611](https://github.com/neomutt/neomutt/releases/latest).
Please can you see if this fixes your problem.

**Comment by flatcap** [comment]
@mrkreen 
I guess you're busy.  If you have time, please can you test the new release.  It should fix your problem.

**Comment by mrkreen** [comment]
Sorry - have been quite busy. I still get the following error code when I run mutt:

```
/var/mail/[username]: No such file or directory (errno = 2)
```

I've even gone as far as to create the folders and am still getting the errors.

**Comment by flatcap** [comment]
Hmm... Sorry, I'll keep thinking...

**Comment by flatcap** [comment]
Hi @mrkreen, I hope you haven't given up on NeoMutt.
I found some time and had a **good** look at what might be happening.

The only part of Mutt that refers to `/var/mail/` is `$spoolfile`.  This should be set to the place where incoming mail will arrive.  On a Unix box that's often `/var/mail/{username}`.  Check what yours is set to with:
```
mutt -D | grep spoolfile
```

Also, check if the "homespool" setting is enabled:

```
mutt -v | grep HOMESPOOL
```

The code looks for settings in this order:
1. User sets it in muttrc, e.g. `set spoolfile=~/mbox`
2. Environment variable `MAIL` is set
3. Environment variable `MAILDIR` is set
4. `+HOMESPOOL`, e.g. `./configure --with-homespool=/home/flatcap/inbox`
5. `-HOMESPOOL`, concatenate `/var/mail/` with your username, e.g. `/var/mail/mrkreen`

You are number 5 :-)

If you set a value for `spoolfile`, I think the errors will go away.

**Comment by mrkreen** [comment]
Richard,

I've been swamped in other things and will have to re-approach this very soon. I'm also getting ready to move into a new machine, so I am limiting anything really new before I transition over. I will however cobble together a config file that better defines some of this and let you know of the results here as soon as I can. Thanks for all the assistance with this.

@mrkreen
Jon Siddle


On Jul 05, 2016, at 05:46 PM, Richard Russon <notifications@github.com> wrote:

Hi @mrkreen, I hope you haven't given up on NeoMutt.
I found some time and had a good look at what might be happening.
The only part of Mutt that refers to /var/mail/ is $spoolfile. This should be set to the place where incoming mail will arrive. On a Unix box that's often /var/mail/{username}. Check what yours is set to with:
mutt -D | grep spoolfile
Also, check if the "homespool" setting is enabled:
mutt -v | grep HOMESPOOL
The code looks for settings in this order:
1. User sets it in muttrc, e.g. set spoolfile=~/mbox
2. Environment variable MAIL is set
3. Environment variable MAILDIR is set
4. +HOMESPOOL, e.g. ./configure --with-homespool=/home/flatcap/inbox
5. -HOMESPOOL, concatenate /var/mail/ with your username, e.g. /var/mail/mrkreen
You are number 5 :-)
If you set a value for spoolfile, I think the errors will go away.

**Comment by flatcap** [comment]
Hi again @mrkreen, I'd love to close this bug, some day :-)

I haven't done anything, recently, to address your problem.
If you're still having issues, I'd at least like to start debugging from a newer release.
The latest NeoMutt is 2016-08-08.

**Comment by mrkreen** [comment]
Richard,

I was finally able to set the spool file in config and everything worked out fine. Still fine tuning my config to where I can send properly but I can at least get email to come in.

Thanks for checking in and sorry for the very long delay in this bug.

-mk

On Aug 07, 2016, at 07:29 PM, Richard Russon <notifications@github.com> wrote:

Hi again @mrkreen, I'd love to close this bug, some day :-)
I haven't done anything, recently, to address your problem.
If you're still having issues, I'd at least like to start debugging from a newer release.
The latest NeoMutt is 2016-08-08.

**Comment by flatcap** [comment]
> everything worked out fine

great

> sorry for the very long delay in this bug

No problem :-)
