### ISSUE TITLE
Seg Fault on folder purge

### ISSUE THREAD

**Issue by tristancollins** [neomutt/neomutt#642]
Apologies if this is in the incorrect format. Also, I've no idea how to bug trace with mutt...

    * Marking mail item(s) for deletion (not for moving to trash) then issuing a sync mailbox command should purge the message and return you to the message pane.
    * Every so often, when the command to sync is made, mutt closes with a segmentation Error.
    * Intermittent - but didn't happen in previous versions.
    * NeoMutt 20170609 (1.8.3)
```
System: Darwin 16.6.0 (x86_64)
slang: 20204
libidn: 1.33 (compiled with 1.33)
hcache backends: gdbm

Compiler:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--prefix=/opt/local' '--disable-debug' '--disable-gpgme' '--enable-notmuch' '--disable-silent-rules' '--disable-warnings' '--mandir=/opt/local/share/man' '--with-docdir=/opt/local/share/doc/mutt' '--with-libiconv-prefix=/opt/local' '--with-slang=/opt/local' '--without-bdb' '--with-gdbm=/opt/local' '--without-gnutls' '--without-gss' '--with-idn=/opt/local' '--without-kyotocabinet' '--without-lmdb' '--without-qdbm' '--with-sasl=/opt/local' '--with-ssl=/opt/local' '--without-tokyocabinet' 'CC=/usr/bin/clang' 'CFLAGS=-pipe -Os -arch x86_64' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64' 'CPPFLAGS=-I/opt/local/include'

Compilation CFLAGS: -pipe -Os -arch x86_64

Compile options:
  +attach_headers_color -bkgdset +color +compose_to_sender +compress +cond_date
  -curs_set -debug -dotlock +encrypt_to_self -exact_address +fcntl -flock
  -fmemopen +forgotten_attachments +forwref -futimens +getaddrinfo +getsid
  -gnutls -gpgme -gss +hcache -homespool -iconv_nontrans +ifdef +imap
  +index_color +initials +keywords +libidn +limit_current_thread +lmdb
  -locales_hack -lua -meta -mixmaster +multiple_fcc +nested_if +new_mail +nls
  +nntp +notmuch +openssl +pgp +pop +progress +quasi_delete +regcomp
  +reply_with_xorig -resizeterm +sasl +sensible_browser -setgid +sidebar
  +skip_quoted +smime +smtp -start_color +status_color +sun_attachment +timeout
  +tls_sni +trash -typeahead +wc_funcs
```

**Comment by tristancollins** [comment]
Here is a copy / paste from when it happens. You can see the lower line of the message pane, the statues message followed by the seg fault message, then you are dumped back at the command prompt.

```
─── Meta: =INBOX ─── [*229 messages (3 new) (1 to delete) ]──────────────────────────────────────
Expunging messages from server...Segmentation fault: 11
Boko:~$
```

**Comment by flatcap** [comment]
> but didn't happen in previous versions

Hmm... We haven't touch the trash/purge code recently.
Do you remember which version you were using that was stable?

**Comment by tristancollins** [comment]
Most likely it was 20170428 - I use MacPorts and see there was a couple of updates in quick succession.

There may be a related issue - I see many more "Mailbox was externally modified.  Flags may be wrong." warnings when updating a mailbox. Simply adding a New flag to a message and syncing the mailbox causes this. Or reading new mail then syncing does likewise. Again, this didn't happen before.

**Comment by nerdyshelties** [comment]
I'm having the same issue - here is the error message:

`Expunging messages from server...[1]    85554 segmentation fault  mutt -d 5`

And the debug data if it is helpful:

```
[2017-07-02 23:38:54] 8> a0334 NOOP^M
[2017-07-02 23:38:54] 8< * 1 EXPUNGE
[2017-07-02 23:38:54] Handling EXPUNGE
[2017-07-02 23:38:54] 8< * 19 EXPUNGE
[2017-07-02 23:38:54] Handling EXPUNGE
[2017-07-02 23:38:54] 8< * 22 EXPUNGE
[2017-07-02 23:38:54] Handling EXPUNGE
[2017-07-02 23:38:54] 8< * 23 EXPUNGE
[2017-07-02 23:38:54] Handling EXPUNGE
[2017-07-02 23:38:54] 8< * 23 EXPUNGE
[2017-07-02 23:38:54] Handling EXPUNGE
[2017-07-02 23:38:54] 8< * 23 EXISTS
[2017-07-02 23:38:54] Handling EXISTS
[2017-07-02 23:38:54] 8< * 0 RECENT
[2017-07-02 23:38:54] 8< a0334 OK Completed
[2017-07-02 23:38:54] IMAP queue drained

```
Version and configuration:

```
NeoMutt 20170609 (1.8.3)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 16.6.0 (x86_64)
hcache backends: tokyocabinet

Compiler:
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: '--prefix=/usr/local/Cellar/neomutt/20170609' '--with-ssl=/usr/local/opt/openssl' '--with-sasl' '--with-gss' '--with-tokyocabinet' '--enable-notmuch' '--enable-debug' 'CC=clang'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -g -O2

Compile options:
  +attach_headers_color +bkgdset +color +compose_to_sender +compress +cond_date
  +curs_set +debug -dotlock +encrypt_to_self -exact_address +fcntl -flock
  -fmemopen +forgotten_attachments +forwref -futimens +getaddrinfo +getsid
  -gnutls -gpgme +gss +hcache -homespool -iconv_nontrans +ifdef +imap
  +index_color +initials +keywords -libidn +limit_current_thread +lmdb
  -locales_hack -lua +meta -mixmaster +multiple_fcc +nested_if +new_mail +nls
  +nntp +notmuch +openssl +pgp +pop +progress +quasi_delete +regcomp
  +reply_with_xorig +resizeterm +sasl +sensible_browser -setgid +sidebar
  +skip_quoted +smime +smtp +start_color +status_color +sun_attachment +timeout
  +tls_sni +trash +typeahead +wc_funcs
EXECSHELL="/bin/sh"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20170609/share/mutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20170609/etc"

```

**Comment by tristancollins** [comment]
I think this issue may actually be starting prior to 20170428 (1.8.2). I rolled back to this version and notice an issue on folder syncs which may be related.

Marking messages for deletion (move to trash) then hitting the key for syncing means the messages remain in the Inbox. Hitting sync again does what it's meant to. But now there are two copies of the message in the trash.

This is intermittent, the same across accounts / config files etc.

**Comment by flatcap** [comment]
> I see many more "Mailbox was externally modified

Where is your mail stored?  Local?  mbox or maildir?  IMAP?
Who is updating it?  Or is that just new mail arriving?

**Comment by aradici** [comment]
I have similar reports in Debian of a case of segfault with a mailbox externally updated, it seems to happen in the hdr_format_str code if I'm not wrong

**Comment by tristancollins** [comment]
This issue(s) is still happening as of neomutt 20170912: 

`NeoMutt 20170912 (1.9.0)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 16.7.0 (x86_64)
ncurses: ncurses 6.0.20170916 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)
hcache backends: gdbm

Compiler:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--prefix=/opt/local' '--disable-debug' '--disable-gpgme' '--enable-notmuch' '--disable-silent-rules' '--mandir=/opt/local/share/man' '--with-docdir=/opt/local/share/doc/mutt' '--with-libiconv-prefix=/opt/local' '--with-curses=/opt/local' '--without-bdb' '--with-gdbm=/opt/local' '--without-gnutls' '--without-gss' '--with-idn=/opt/local' '--without-kyotocabinet' '--without-lmdb' '--without-qdbm' '--with-sasl=/opt/local' '--with-ssl=/opt/local' '--without-tokyocabinet' 'CC=/usr/bin/clang' 'CFLAGS=-pipe -Os -arch x86_64' 'LDFLAGS=-L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64' 'CPPFLAGS=-I/opt/local/include'

Compilation CFLAGS: -Wall -pedantic -pipe -Os -arch x86_64

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +keywords +limit_current_thread +multiple_fcc +nested_if +new_mail
  +nntp +pop +progress +quasi_delete +regcomp +reply_with_xorig
  +sensible_browser +sidebar +skip_quoted +smtp +status_color +timeout +tls_sni
  +trash

Compile options:
  +bkgdset +color +curs_set -debug +fcntl -flock -fmemopen -futimens
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn -locales_hack -lua
  +meta -mixmaster +nls +notmuch +openssl +pgp +resizeterm +sasl +smime
  +start_color +sun_attachment +typeahead
ISPELL="/opt/local/bin/ispell"
MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/mutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"`

Output of mutt -D -S:

`abort_noattach=no
abort_nosubject=ask-yes
abort_unmodified=yes
alias_file="~/.mutt/aliases"
alias_format="%4n %2f %t %-10a   %r"
allow_8bit is set
allow_ansi is unset
arrow_cursor='***'
ascii_chars is unset
askbcc is unset
askcc is unset
ask_follow_up is unset
ask_x_comment_to is unset
assumed_charset=""
attach_charset=""
attach_format="%u%D%I %t%4n %T%.40d%> [%.7m/%.10M, %.6e%?C?, %C?, %s] "
attach_keyword="\\<(attach|attached|attachments?)\\>"
attach_sep=""
attach_split is set
attribution="On %d, %n wrote:"
attribution_locale=""
auto_tag is unset
autoedit is unset
beep is set
beep_new is unset
bounce=ask-yes
bounce_delivered is set
braille_friendly is unset
catchup_newsgroup=ask-yes
certificate_file="~/.mutt/certificates"
charset="utf-8"
check_mbox_size is unset
check_new is set
collapse_unread is set
collapse_flagged is set
compose_format='***'
config_charset=""
confirmappend is unset
confirmcreate is set
connect_timeout=30
content_type="text/plain"
copy=yes
crypt_autoencrypt is unset
crypt_autopgp is set
crypt_autosign is unset
crypt_autosmime is set
crypt_confirmhook is set
crypt_opportunistic_encrypt is unset
crypt_replyencrypt is set
crypt_replysign is unset
crypt_replysignencrypted is unset
crypt_timestamp is set
crypt_use_gpgme is unset
crypt_use_pka is unset
crypt_verify_sig=yes
date_format='***'
default_hook="~f %s !~P | (~P ~C %s)"
delete=yes
delete_untag is set
digest_collapse is set
display_filter=""
dsn_notify=""
dsn_return=""
duplicate_threads is set
edit_headers is set
editor="emacs +8 %s"
empty_subject="Re: your mail"
encode_from is unset
entropy_file=""
envelope_from_address=""
escape="~"
fast_reply is unset
fcc_attach=yes
fcc_clear is unset
flag_safe is unset
folder="imaps://imap.xxxxxxxxxxx.com:993/"
folder_format='***'
followup_to is set
followup_to_poster=ask-yes
force_name is unset
forward_attribution_intro="----- Forwarded message from %f -----"
forward_attribution_trailer="----- End forwarded message -----"
forward_decode is set
forward_decrypt is set
forward_edit=yes
forward_format="Fwd: %s"
forward_quote is unset
forward_references is unset
from="yyyyyyy@xxxxxxxxxxx.net"
from_chars=""
gecos_mask="^[^,]*"
group_index_format="%4C %M%N %5s  %-45.45f %d"
hdrs is set
header is unset
header_cache="~/.mutt/cache/headers"
header_cache_backend=""
header_cache_pagesize="16384"
header_color_partial is unset
help is set
hidden_host is unset
hide_limited is unset
hide_missing is set
hide_thread_subject is set
hide_top_limited is unset
hide_top_missing is set
history=10
history_file="~/.mutthistory"
history_remove_dups is unset
honor_disposition is unset
honor_followup_to=yes
hostname="zzzzzzzzzz.local"
idn_decode='***'
idn_encode='***'
ignore_linear_white_space is unset
ignore_list_reply_to is unset
show_multipart_alternative=""
imap_authenticators=""
imap_check_subscribed is unset
imap_delim_chars="/."
imap_headers=""
imap_idle is set
imap_keepalive=900
imap_list_subscribed is unset
imap_login='***'
imap_pass='***'
imap_passive is unset
imap_peek is set
imap_pipeline_depth=15
imap_poll_timeout=15
imap_servernoise is set
imap_user='***'
implicit_autoview is unset
include=ask-yes
include_onlyfirst is unset
indent_string="> "
index_format="%3C %Z %D %-18.18L %4c %s"
inews=""
ispell="/opt/local/bin/ispell"
keep_flagged is unset
keywords_legacy is set
keywords_standard is unset
mail_check=5
mail_check_recent is set
mail_check_stats is unset
mail_check_stats_interval=60
mailcap_path="~/.mailcap"
mailcap_sanitize is set
maildir_header_cache_verify is set
maildir_trash is unset
maildir_check_cur is unset
mark_macro_prefix="'"
mark_old is unset
markers is unset
mask="!^\\.[^.]"
mbox="~/mbox"
mbox_type=mbox
menu_context=0
menu_move_off is set
menu_scroll is unset
message_cache_clean is unset
message_cachedir="~/.mutt/cache/bodies"
message_format="%s"
meta_key is unset
metoo is unset
mh_purge is unset
mh_seq_flagged="flagged"
mh_seq_replied="replied"
mh_seq_unseen="unseen"
mime_forward=no
mime_forward_decode is unset
mime_forward_rest=yes
mime_subject is set
mime_type_query_command=""
mime_type_query_first is unset
move=no
narrow_tree is unset
net_inc=10
new_mail_command=""
news_cache_dir="~/.mutt"
news_server=""
newsgroups_charset="utf-8"
newsrc="~/.newsrc"
nntp_authenticators=""
nntp_context=1000
nntp_listgroup is set
nntp_load_description is set
nntp_user='***'
nntp_pass='***'
nntp_poll=60
nm_open_timeout=5
nm_default_uri=""
nm_hidden_tags="unread,draft,flagged,passed,replied,attachment,signed,encrypted"
nm_exclude_tags=""
nm_unread_tag="unread"
nm_db_limit=0
nm_query_type="messages"
nm_record is unset
nm_record_tags=""
nm_query_window_duration=0
nm_query_window_timebase="week"
nm_query_window_current_search=""
nm_query_window_current_position=0
pager="builtin"
pager_context=5
pager_format="-%Z- %C/%m: %-20.20n   %s%*  -- (%P)"
pager_index_lines=10
pager_stop is set
pgp_auto_decode is unset
pgp_autoinline is unset
pgp_check_exit is set
pgp_clearsign_command=""
pgp_decode_command=""
pgp_decrypt_command=""
pgp_decryption_okay=""
pgp_encrypt_only_command=""
pgp_encrypt_sign_command=""
pgp_entry_format="%4n %t%f %4l/0x%k %-4a %2c %u"
pgp_export_command=""
pgp_getkeys_command=""
pgp_good_sign=""
pgp_ignore_subkeys is set
pgp_import_command=""
pgp_list_pubring_command=""
pgp_list_secring_command=""
pgp_long_ids is set
pgp_mime_auto=ask-yes
pgp_replyinline is unset
pgp_retainable_sigs is unset
pgp_self_encrypt is unset
pgp_self_encrypt_as=""
pgp_show_unusable is set
pgp_sign_as=""
pgp_sign_command=""
pgp_sort_keys=address
pgp_strict_enc is set
pgp_timeout=300
pgp_use_gpg_agent is unset
pgp_verify_command=""
pgp_verify_key_command=""
pipe_decode is unset
pipe_sep=""
pipe_split is unset
pop_auth_try_all is set
pop_authenticators=""
pop_checkinterval=60
pop_delete=ask-no
pop_host=""
pop_last is unset
pop_pass='***'
pop_reconnect=ask-yes
pop_user='***'
post_indent_string=""
post_moderated=ask-yes
postpone=ask-yes
postponed="=Drafts"
postpone_encrypt is unset
postpone_encrypt_as=""
preconnect=""
print=ask-no
print_command="muttprint -p - | ps2pdf - muttprint.pdf"
print_decode is set
print_split is unset
prompt_after is set
query_command="~/.bin/bin/muttqt -q '%s'"
query_format="%4c %t %-25.25a %-25.25n %?e?(%e)?"
quit=yes
quote_regexp="^([ ]*[|>:}#])+"
read_inc=10
read_only is unset
realname="xxxxxxx xxxxxxxx"
recall=ask-yes
record="=Sent Items"
reflow_space_quotes is set
reflow_text is set
reflow_wrap=78
reply_regexp="^(re([\\[0-9\\]+])*|aw):[ ]*"
reply_self is unset
reply_to=ask-yes
reply_with_xorig is unset
resolve is set
resume_draft_files is unset
resume_edited_draft_files is set
reverse_alias is unset
reverse_name is set
reverse_realname is set
rfc2047_parameters is unset
save_address is unset
save_empty is set
save_history=0
save_name is unset
score is set
score_threshold_delete=-1
score_threshold_flag=9999
score_threshold_read=-1
search_context=0
send_charset="us-ascii:iso-8859-1:utf-8"
sendmail="/usr/sbin/sendmail -oem -oi"
sendmail_wait=0
shell="/bin/bash"
save_unsubscribed is unset
show_new_news is set
show_only_unread is unset
sidebar_delim_chars="/."
sidebar_divider_char=""
sidebar_folder_indent is unset
sidebar_format="%B%*  %n"
sidebar_indent_string="  "
sidebar_new_mail_only is unset
sidebar_next_new_wrap is unset
sidebar_on_right is unset
sidebar_short_path is unset
sidebar_sort_method=mailbox-order
sidebar_visible is unset
sidebar_width=30
sig_dashes is set
sig_on_top is unset
signature=""
simple_search="~f %s | ~s %s"
skip_quoted_offset=0
sleep_time=1
smart_wrap is set
smileys="(>From )|(:[-^]?[][)(><}{|/DP])"
smime_ask_cert_label is set
smime_ca_location=""
smime_certificates=""
smime_decrypt_command=""
smime_decrypt_use_default_key is set
smime_default_key=""
smime_encrypt_command=""
smime_encrypt_with="aes256"
smime_get_cert_command=""
smime_get_cert_email_command=""
smime_get_signer_cert_command=""
smime_import_cert_command=""
smime_is_default is unset
smime_keys=""
smime_pk7out_command=""
smime_self_encrypt is unset
smime_self_encrypt_as=""
smime_sign_command=""
smime_sign_digest_alg="sha256"
smime_timeout=300
smime_verify_command=""
smime_verify_opaque_command=""
smtp_authenticators=""
smtp_pass='***'
smtp_url='***'
sort=threads
sort_alias=alias
sort_aux=reverse-last-date-received
sort_browser=date
sort_re is set
spam_separator=","
spoolfile="imaps://imap.xxxxxxxxxx.com:993/"
ssl_client_cert=""
ssl_force_tls is unset
ssl_starttls=yes
ssl_use_sslv2 is unset
ssl_use_sslv3 is unset
ssl_use_tlsv1 is set
ssl_use_tlsv1_1 is set
ssl_use_tlsv1_2 is set
ssl_usesystemcerts is set
ssl_verify_dates is set
ssl_verify_host is set
ssl_verify_partial_chains is unset
ssl_ciphers=""
status_chars="-*%A"
status_format="─── M-Force: %f ─── [%r%m messages%?n? (%n new)?%?d? (%d to delete)?%?t? (%t tagged)? ]───%>─%?p?( %p postponed )?───"
status_on_top is unset
strict_threads is set
suspend is set
text_flowed is unset
thorough_search is set
thread_received is unset
tilde is unset
time_inc=0
timeout=15
tmpdir="/var/folders/hv/w4f40yw55bj3vkx8xvw47_cr0000gp/T/"
to_chars=" +TCFL"
flag_chars="*!DdrONon- "
trash="=Trash"
ts_icon_format="M%?n?AIL&ail?"
ts_enabled is unset
ts_status_format="NeoMutt with %?m?%m messages&no messages?%?n? [%n NEW]?"
tunnel=""
uncollapse_jump is unset
uncollapse_new is set
use_8bitmime is unset
use_domain is set
use_envelope_from is unset
use_from is set
use_ipv6 is set
user_agent is set
visual="vi"
vfolder_format="%2C %?n?%4n/&     ?%4m %f"
virtual_spoolfile is unset
wait_key is set
weed is set
wrap=0
wrap_headers=78
wrap_search is set
wrapmargin=0
write_bcc is set
write_inc=10
xlabel_delimiter=""
x_comment_to is unset
collapse_all is unset
pgp_encrypt_self=no
smime_encrypt_self=no`

**Comment by tristancollins** [comment]
As of release 20171013 I think the issues I described are fixed or less frequent.

**Comment by muziejus** [comment]
I still get this problem:

```
[1]    45880 segmentation fault  neomutt
```

It happens intermittently but often, both when I trigger a purge with `$` and when I quit neomutt. It's talking to a gmail imap server, so maybe that's related to the problem. It occurs whether I have gmail open in a browser window or not.

```
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.6.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/usr/local/Cellar/neomutt/20200626 --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses --lua --with-lua=/usr/local/opt/lua

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/opt/libassuan/include -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/neomutt/20200626/include -I/usr/local/opt/lua/include/lua5.3 -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20200626/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20200626/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
