### ISSUE TITLE
view-attach opens pre-existing file with the same name

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#990]
## Bug report

* Expected behavior: selected attachment should be opened
* Actual behavior: if a file already exists with the same name, this old version is opened instead
* Steps to reproduce:
1. `view-attachments` for a message
2. Select and open an attachment with `view-attach` or `view-mailcap`
3. File is opened and saved to `$tmpdir` (which is `/tmp/mutt` for me)
4. Repeat 1–2 for another email, which has a different attachment with the same name as above
5. The old (existing) attachment is opened instead
* Alternatively way to reproduce: manually save a file as the attachment name
1. Find an email with a pdf attachment
2. Find a different pdf on your computer and copy it to `$tmpdir`, naming it the same as the attachment above
3. Attempt to open the attachment
4. The existing attachment is opened instead
5. N.B. this didn't work if the file in 2 was *not* a pdf.
* Used program versions: Neomutt 20171013-2
* Operating System and its version: Arch Linux (up-to-date)

## Additional comments

In a real-world example, I was sent an updated version of a file, but neomutt opened the old version.

Ideally, Neomutt should check to see if the new version differs. In practice, it's probably just easiest to open the newer version without checking.

**Comment by protist** [comment]
I've been bitten by this again, when people send me things like `screenshot.png` or `attachment.jpg`. Is there a workaround of some kind?

I tried something like 

    macro attach <Return> "<save-entry><kill-line>/tmp/mutt/<Enter>y<Enter>; /usr/bin/xdg-open …"

However, sometimes there is a question to overwrite after the final `<Enter>`, and I also don't know what to use as an argument to `/usr/bin/xdg-open`.

**Comment by roccoblues** [comment]
Hi @protist can you still reproduce this with the latest version? I just tried and couldn't.

**Comment by protist** [comment]
@roccoblues I can still reproduce it under certain conditions with the latest neomutt 20241212.

If I do not set `tmpdir`, neomutt seems to default to saving attachments in `/tmp/mutt`. I can indeed still reproduce this bug, testing the "Alternative way to reproduce" from my original post. i.e. the pre-existing file will be opened instead.

However, if I manually `set tmpdir = /tmp/mutt`, this fixes the bug. Specifically, neomutt attempts to save the file to `/tmp/mutt/foo.pdf`, *unless* there is already a file there, in which case it saves a new copy, e.g. at `/tmp/mutt/foo-message-1000-222587-6977652567131469760.pdf`, then the subsequent copy at `/tmp/mutt/foo-message-1000-222587-9209919306036441084.pdf`, etc. It creates a new copy even if I'm opening the same attachment. After quitting neomutt, these files are removed. This seems like a reasonable solution to me.

However, related to #657, I prefer my drafts saved in a non-volatile location. Oddly enough, if I `set tmpdir = ~/.mutt/tmp`, then attachments appear to be saved to *both* `~/.mutt/tmp` and `/tmp/mutt`. Further, the attachment in `/tmp/mutt` is the one that is opened. This duplication seems like a bug. FWIW I still get the behaviour in the previous paragraph, with new version re-saved, potentially under a new filename.

However, since the file in `/tmp/mutt` is the one being opened, I can force strange behaviour.

1. Put `foo.pdf` in `/tmp/mutt`
2. In neomutt, open an attachment `foo.pdf`
3. `foo.pdf` saves to `~/.mutt/tmp`, as expected. It does not overwrite `/tmp/mutt/foo.pdf`
4. The wrong version `/tmp/mutt/foo.pdf` is opened.

So it seems this reveals another bug. If `tmpdir` is set, then neomutt saves to both `tmpdir` and `/tmp/mutt`, but opens attachments in `/tmp/mutt`.

Finally, after quitting mutt, it cleans up saved attachments in `~/mutt/tmp`, but *not* in `/tmp/mutt`.

**Comment by roccoblues** [comment]
> neomutt attempts to save the file to /tmp/mutt/foo.pdf, unless there is already a file there, in which case it saves a new copy, e.g. at /tmp/mutt/foo-message-1000-222587-6977652567131469760.pdf, then the subsequent copy at /tmp/mutt/foo-message-1000-222587-9209919306036441084.pdf, etc.

yes, that is what I'm getting too. With and without `set tmp_dir`.

> So it seems this reveals another bug. If tmpdir is set, then neomutt saves to both tmpdir and /tmp/mutt, but opens attachments in /tmp/mutt.

Sorry, I had another look and I can't reproduce this. Also looking at the code I'd be very surprised if it would behave that way. Can you double check that you weren't looking at some old attachment or something similar?

**Comment by protist** [comment]
> Can you double check that you weren't looking at some old attachment or something similar?

I actually tested this extensively for about an hour yesterday, including numerous permutations, so I'm sure it's a real thing.

Maybe it's something in my config? My muttrc is >400 lines and super messy, so I don't really want to sanitise it to post here. Are there particular settings that I can isolate? Otherwise I can try and create a minimal failing config, although this might be a bit painful.

**Comment by roccoblues** [comment]
ok, a couple of more things to check:

* When switching between set/unset `tmp_dir`, do you change your muttrc and restart or edit the config on the fly?
* Please check `echo $tmp_dir` and `echo $tmpdir` from inside neomutt before opening the attachment in both cases. What does it say?

> If I do not set tmpdir, neomutt seems to default to saving attachments in /tmp/mutt

This seems suspicious, it should default to `$TMPDIR`. What does `echo $TMPDIR` show in the shell session before you start neomutt?

**Comment by roccoblues** [comment]
one more thing, just to double check:

> ~/.mutt/tmp and /tmp/mutt

any chance one of those is a symlink to the other?

**Comment by protist** [comment]
> When switching between set/unset `tmp_dir`, do you change your muttrc and restart or edit the config on the fly?

In my testing I would quit mutt, edit muttrc, then relaunch mutt.

> Please check...

With `set tmpdir = ~/.mutt/tmp`

```
:echo $tmp_dir
/home/protist/.mutt/tmp
:echo $tmpdir
/home/protist/.mutt/tmp
```

With either `set tmpdir` or `set tmpdir = /tmp`, both commands give `/tmp`.

> What does echo `$TMPDIR` show in the shell session before you start neomutt?

`$TMPDIR` is empty.

> any chance one of those is a symlink to the other?

No definitely not. Also [above](https://github.com/neomutt/neomutt/issues/990#issuecomment-2574384214) I can force each directory to have different behaviour (e.g. save to only one; clean up only one).

**Comment by roccoblues** [comment]
The `tmpdir` handling might have been fixed in NeoMutt 20260616: https://github.com/neomutt/neomutt/issues/4914#issuecomment-5150638967.

**Comment by protist** [comment]
> The `tmpdir` handling might have been fixed in NeoMutt 20260616: [#4914 (comment)](https://github.com/neomutt/neomutt/issues/4914#issuecomment-5150638967).

Just to update in this thread, the linked thread suggests the other way around. i.e. it wasn't fixed but introduced in 20260616.
